### ISSUE TITLE
Run containers on non-default subnet

### ISSUE THREAD

**Issue by btsherid** [DigitalSlideArchive/digital_slide_archive#110]
Hi,

Is there an option to run these containers on a different subnet than the docker default 172.17.x.x?

Unfortunately our VPN subnet is on 172.17.x.x, so when docker_deploy.sh starts the containers, it creates a static route that immediately kills all access to the server from the VPN.

Thanks,
Brendan

**Comment by manthey** [comment]
By default we use the docker network named "dsa".  If you precreate the network with a different subnet, then it will use that instead of creating it as part of deploy_docker.py.  For instance, `docker network create --subnet 172.19.0.0/16 dsa` and then `deploy_docker.py`.

We remove the network when you do `deploy_docker.py rm`, so you'll have to recreate it each time or modify the code.

**Comment by btsherid** [comment]
Thanks. That worked.
